# Generated by Django 5.1.6 on 2025-02-26 18:03

import django.db.models.deletion
import django.utils.timezone
import vendas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cnpj", models.CharField(max_length=255)),
                ("inscricao_estadual", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=255)),
                ("rg", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=255)),
                ("endereco", models.CharField(max_length=255)),
                ("cep", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=255)),
                ("bairro", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                (
                    "codigo_cliente",
                    models.CharField(default="bcd9ca", editable=False, max_length=6),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_cadastro", models.DateField(auto_now_add=True)),
                ("data_vencimento", models.DateField()),
                ("pago", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=255)),
                ("razao_social", models.CharField(max_length=255)),
                ("endereco", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=20)),
                ("bairro", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                ("cidade", models.CharField(max_length=100)),
                ("complemento", models.CharField(blank=True, max_length=255)),
                ("contato", models.CharField(max_length=100)),
                ("inscricao_estadual", models.CharField(max_length=20)),
                ("cnpj", models.CharField(max_length=20, unique=True)),
                ("inscricao_municipal", models.CharField(max_length=20)),
                ("cep", models.CharField(max_length=10)),
                ("regime_tributario", models.CharField(max_length=100)),
                ("dados_sintegra", models.CharField(blank=True, max_length=255)),
                ("telefone", models.CharField(max_length=20)),
                ("ibge_municipio", models.CharField(max_length=10)),
                ("ibge_estado", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Imposto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icms", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ipi", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pis", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cofins", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cfop", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("grupo", models.CharField(max_length=255)),
                ("marca", models.CharField(max_length=255)),
                ("unidade_medida", models.CharField(max_length=255)),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "codigo_produto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantidade", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_vendedor", models.CharField(max_length=255)),
                ("codigo_vendedor", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="NFe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=255)),
                ("serie", models.CharField(max_length=255)),
                ("data_emissao", models.DateField()),
                ("emitente_nome", models.CharField(max_length=255)),
                ("emitente_cnpj", models.CharField(max_length=255)),
                ("emitente_endereco", models.CharField(max_length=255)),
                ("destinatario_nome", models.CharField(max_length=255)),
                ("destinatario_cnpj", models.CharField(max_length=255)),
                ("destinatario_endereco", models.CharField(max_length=255)),
                ("forma_pagamento", models.CharField(max_length=255)),
                ("transporte_modalidade", models.CharField(max_length=255)),
                ("transporte_codigo", models.CharField(max_length=255)),
                ("chave_acesso", models.CharField(max_length=255)),
                ("impostos", models.ManyToManyField(to="vendas.imposto")),
                ("produtos", models.ManyToManyField(to="vendas.produto")),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_venda", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "desconto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "acrescimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "id_venda",
                    models.CharField(
                        default=vendas.models.gerar_id_venda, max_length=11, unique=True
                    ),
                ),
                ("pago", models.BooleanField(default=False)),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("cartao_credito", "Cartão de Crédito"),
                            ("boleto", "Boleto"),
                            ("conta_cliente", "Conta do Cliente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendas.cliente"
                    ),
                ),
                (
                    "nome_vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendas.vendedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendas.produto"
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="vendas.venda",
                    ),
                ),
            ],
        ),
    ]
