# Generated by Django 5.1.6 on 2025-02-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="codigo_cliente",
            field=models.CharField(default="baf9d4", editable=False, max_length=6),
        ),
    ]
