# Generated by Django 5.1.6 on 2025-02-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_alter_cliente_codigo_cliente"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venda",
            old_name="nome_vendedor",
            new_name="vendedor",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigo_cliente",
            field=models.CharField(default="6476a9", editable=False, max_length=6),
        ),
    ]
