# Generated by Django 5.1.6 on 2025-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0003_rename_nome_vendedor_venda_vendedor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="codigo_cliente",
            field=models.CharField(default="ab2e1d", editable=False, max_length=6),
        ),
    ]
