# Generated by Django 5.1.6 on 2025-02-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0004_alter_cliente_codigo_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("finalizada", "Finalizada")],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigo_cliente",
            field=models.CharField(default="b97ee0", editable=False, max_length=6),
        ),
    ]
