# Generated by Django 5.1.6 on 2025-02-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=255)),
                ("inscricao_estadual", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=255)),
                ("rg", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=255)),
                ("endereco", models.CharField(max_length=255)),
                ("cep", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=255)),
                ("bairro", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("grupo", models.CharField(max_length=255)),
                ("marca", models.CharField(max_length=255)),
                ("unidade_medida", models.CharField(max_length=255)),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendas.cliente",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendas.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_venda", models.DateField(auto_now_add=True)),
                ("quantidade", models.IntegerField(default=1)),
                (
                    "desconto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("id_venda", models.CharField(max_length=11, unique=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendas.cliente"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendas.produto"
                    ),
                ),
            ],
        ),
    ]
