# Generated by Django 5.1.6 on 2025-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.CharField(default='19ae3a', editable=False, max_length=6),
        ),
    ]
